contacts:
  name: Amir
  lastName: Soufi Doost
  title: Junior Software Engineer
  email: iampoxel6@gmail.com
  address: "Mashhad, Iran"
  location: Iran
  github:
    url: https://github.com/PoXel6
    displayText: "github.com/poxel6"
  exp:
    url: https://poxel6.github.io/PoXel6
    displayText: "2+ years experience"

position: Junior Software Engineer

tagline: Junior Software engineer with 2 years of experience with a strong foundation in computer science, and a natural problem-solver.  Proficient in Java, Kotlin, JavaScript/TypeScript, and Rust with a solid understanding of system architecture and design principles.

jobs:
  - position: Fake Company
    company:
      name: FakeCompany LTD
      link: "https://msht.sh"
    product:
      name: ThisThat
      link: https://thisthat.com
    description:
      - something
    from: "2019 Jan."
    to: "2019 Dec."
    tags:
      - Quality Assurance
      - Testing
      - Automation
    location: Austin, USA

objective: Seeking to advance my skills and build a strong career with a company that values innovation and creativity.

projects:
  - name: "Twitter Clone"
    from: "July 2026"
    to: "August 2026"
    link: "https://github.com/PoXel6/twitter-clone.git"
    description: "Twitter clone written in Kotlin with spring boot, frontend is powered by NextJS, Tailwindcss and Shadcn."
    stack: "Kotlin, Spring Boot, NextJS, Typstscript, Tailwindcss, REST API"
  - name: "JLOX"
    from: "March 2026"
    to: "July 2026"
    link: "https://github.com/PoXel6/jlox.git"
    description: "Lox interpreter written in java. Parsing is powered by Recursive-Decent. It leverages Visitor Design Pattern and a custom meta-programming script to generate it's AST. It follows SOLID, DRY, and YAGNI principles."
    stack: "Java, Gradle, Intellij IDEA, Meta Programming, Design Patterns, Intellij IDEA"
  - name: "NEWJ"
    from: "July 2025"
    to: "Oct 2025"
    link: "https://github.com/PoXel6/newj.git"
    description: "Simple CLI tool to generate Java project structure. has Gradle dependency presets for different application. currently has: Minecraft, Simple, Spring. Hydrates generated files with templates. sane and configurable defaults."
    stack: "Rust, Cargo, NVim, Clip-rs, proc-macros, Performance Aware Programming"

education:
  - place:
      name: Mashhad, Azad University
      link: ""
    degree: B.Sc.
    major: Computer Science
    track: Computer Science
    from: "2025"
    to: "present"
    location: Mashhad, Iran
  - place:
      name: Technical College
      link: ""
    degree: Diploma
    major: Multimedia Design
    track: Multimedia Design
    from: "2023"
    to: "2025"
    location: Mashhad, Iran

technical_expertise:
  - name: Java
    level: 5
  - name: Kotlin
    level: 4
  - name: JavaScript
    level: 5
  - name: TypeScript
    level: 4
  - name: Rust
    level: 3
  - name: Go
    level: 3
  - name: Python
    level: 4

skills:
  - Java
  - Kotlin
  - Rust
  - Python
  - Go
  - JavaScript
  - TypeScript
  - MySQL
  - MariaDB
  - MongoDB
  - SQLite

libs:
  - React
  - Nextjs
  - Tailwindcss
  - Shadcn
  - JUnit
  - Vuejs
  - Spring Boot
  - Ktor
  - Exposed

tools:
  - Git
  - GitHub
  - CI/CD
  - Linux
  - Docker
  - Neovim
  - IntelliJ
  - Gradle
  - Photoshop
